routes/web.php
<?php

include __DIR__ . '/aritsan_routes.php';
Route::get('test',function (){
    return view('vendor\notifications\email');
    $order = \App\Models\Order::whereNotNull('trip_id')->first();
//    dd($order);
    return $order->childrenNamePriceTrip();
});
Route::get('logs', 'LogViewerController@index');

// Authentication Routes...
$this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login')->name('do-login');
$this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/request', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Admin Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for admin role
|	, 'middleware' => ['auth', 'role:admin']
*/
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin|staff']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin']], function () {

    // user managmet
    Route::resource('users', 'AdminController');
    Route::resource('pages', 'PageController');

    // settigns routes group
    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/site_settings', 'SettingController@siteSetting')->name('site');
        Route::post('/site_settings', 'SettingController@storeSiteSetting')->name('store.site');

        Route::get('general', 'SettingController@showGeneral')->name('general');
        Route::post('general', 'SettingController@updateGeneral')->name('general');

        Route::get('mail', 'SettingController@showMail')->name('mail');
        Route::post('mail', 'SettingController@updateMail')->name('mail');

        Route::post('send-email', 'SettingController@sendEmail')->name('send-email');

        Route::get('gateway', 'SettingController@showGateway')->name('gateway');
        Route::get('admin-gateway', 'SettingController@showGatewayAdmin')->name('gateway-admin');
        Route::post('gateway', 'SettingController@updateGateway')->name('gateway');

        Route::delete('{setting_id}/email/{email?}', [
            'as' => 'destroy_email',
            'uses' => 'SettingController@destroy_email'
        ]);

        Route::get('/twilio', 'SettingController@twilioSetting')->name('twilio');
        Route::post('/twilio', 'SettingController@storeTwilioSetting')->name('store.twilio');
        
    });

});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::group(['as'=>'admin.'], function () {
        Route::resource('home', 'HomePageController');
    });
});


/*
|--------------------------------------------------------------------------
| AuthUsers Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for authenticated Users
|
*/

Route::group(['namespace' => 'AuthUsers', 'middleware' => ['auth']], function () {

    Route::get('index', 'SampleController@index')->name('index');

});


/*
|--------------------------------------------------------------------------
| App Guest Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes unauthenticated users
|
*/

Route::group(['namespace' => 'App'], function () {


});


Route::get('log', function () {
    // from PHP documentations
    $logFile = file(storage_path() . '/logs/laravel.log');
    $logCollection = [];
    // Loop through an array, show HTML source as HTML source; and line numbers too.
    foreach ($logFile as $line_num => $line) {
        $logCollection[] = array('line' => $line_num, 'content' => htmlspecialchars($line));
    }
    dump($logFile);
});

Route::get('log/delete', function () {

    $file = storage_path() . '/logs/laravel.log';
    if (unlink($file)) {
        dump('deleted');
    }


});

Route::get('/home', 'FrontendController@homepage')->name('home');

//-------------------- Email Template Module -------------------//
Route::resource('email_templates','EmailTemplateController');
//-------------------- End ------------------------------------//

resources/views/layouts/partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ url('admin/dashboard') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{{ config('general.site_name', 'Laravel Systems')}}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{{ config('general.site_name', 'Laravel Systems') }}</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <ul class="nav navbar-nav navbar-left pull-left">

            <li class="">
                <a href="" class="waves-effect waves-light">
                    <span>Menu</span>
                </a>
            </li>
        </ul>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{assetsUrl()}}/img/user2-160x160.jpg" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ Auth::user()->name }} </span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{assetsUrl()}}/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                            <p>
                                {{ Auth::user()->name }}
                            </p>
                        </li>

                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admin.users.edit', Auth::user()->id) }} "
                                   class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/partials/left.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{assetsUrl()}}/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p> {{ Auth::user()->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-gear"></i>
                    <span>Static Pages</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    @foreach (App\Models\Page::all() as $record )
                        <li><a href="{{url('admin')}}/pages/{{$record->id}}/edit">{{$record->title}}</a></li>
                    @endforeach

                </ul>
            </li>
            @if(!isStaff())
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-gear"></i>
                    <span>Settings</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.users.index')}}"><i class="fa fa-users"></i>Admins</a></li>
                    <li><a href="{{ route('admin.settings.general')}}"><i class="fa fa-globe"></i>General</a></li>
                    <li><a href="{{ route('admin.settings.mail')}}"><i class="fa fa-envelope-o"></i>Mail</a></li>
                    <li>
                        <a href="{{ route('admin.settings.site') }}"><i class="fa  fa-sitemap"></i>Site Settings</a>
                    </li>
                    <li><a href="{{ route('email_templates.index') }}"><i class="fa fa-users"></i>Email Templates</a></li>
                    <li>
                        <a href="{{ route('admin.settings.twilio') }}"><i class="fa fa-comment-o"></i>Twilio
                            Settings</a>
                    </li>
                    <li><a href="{{ route('admin.settings.gateway')}}"><i class="fa fa-credit-card"></i>Gateway</a>
                    </li>
                </ul>
            </li>
                @endif


        </ul>
    </section>
    <!-- /.sidebar -->
</aside>