routes/web.php
<?php

include __DIR__ . '/aritsan_routes.php';
Route::get('test',function (){
    return view('vendor\notifications\email');
    $order = \App\Models\Order::whereNotNull('trip_id')->first();
//    dd($order);
    return $order->childrenNamePriceTrip();
});
Route::get('logs', 'LogViewerController@index');

// Authentication Routes...
$this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login')->name('do-login');
$this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/request', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Admin Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for admin role
|	, 'middleware' => ['auth', 'role:admin']
*/
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin|staff']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin']], function () {

    // user managmet
    Route::resource('users', 'AdminController');
    Route::resource('pages', 'PageController');

    // settigns routes group
    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/site_settings', 'SettingController@siteSetting')->name('site');
        Route::post('/site_settings', 'SettingController@storeSiteSetting')->name('store.site');

        Route::get('general', 'SettingController@showGeneral')->name('general');
        Route::post('general', 'SettingController@updateGeneral')->name('general');

        Route::get('mail', 'SettingController@showMail')->name('mail');
        Route::post('mail', 'SettingController@updateMail')->name('mail');

        Route::post('send-email', 'SettingController@sendEmail')->name('send-email');

        Route::get('gateway', 'SettingController@showGateway')->name('gateway');
        Route::get('admin-gateway', 'SettingController@showGatewayAdmin')->name('gateway-admin');
        Route::post('gateway', 'SettingController@updateGateway')->name('gateway');

        Route::delete('{setting_id}/email/{email?}', [
            'as' => 'destroy_email',
            'uses' => 'SettingController@destroy_email'
        ]);

        Route::get('/twilio', 'SettingController@twilioSetting')->name('twilio');
        Route::post('/twilio', 'SettingController@storeTwilioSetting')->name('store.twilio');
        
    });

});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::group(['as'=>'admin.'], function () {
        Route::resource('home', 'HomePageController');
    });
});


/*
|--------------------------------------------------------------------------
| AuthUsers Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for authenticated Users
|
*/

Route::group(['namespace' => 'AuthUsers', 'middleware' => ['auth']], function () {

    Route::get('index', 'SampleController@index')->name('index');

});


/*
|--------------------------------------------------------------------------
| App Guest Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes unauthenticated users
|
*/

Route::group(['namespace' => 'App'], function () {


});


Route::get('log', function () {
    // from PHP documentations
    $logFile = file(storage_path() . '/logs/laravel.log');
    $logCollection = [];
    // Loop through an array, show HTML source as HTML source; and line numbers too.
    foreach ($logFile as $line_num => $line) {
        $logCollection[] = array('line' => $line_num, 'content' => htmlspecialchars($line));
    }
    dump($logFile);
});

Route::get('log/delete', function () {

    $file = storage_path() . '/logs/laravel.log';
    if (unlink($file)) {
        dump('deleted');
    }


});

Route::get('/home', 'FrontendController@homepage')->name('home');

//-------------------- Email Template Module -------------------//
Route::resource('email_templates','EmailTemplateController');
//-------------------- End ------------------------------------//

app/User.php
<?php

namespace App;

use App\Models\CustomerChild;
use App\Models\CustomerEmail;
use App\Models\CustomerPaymentProfile;
use App\Models\MetaUser;
use App\Models\Order;
use App\Models\Payment;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function metaUser()
    {
        return $this->hasOne(MetaUser::class,'user_id','id');
    }
    public function orders(){
        return $this->hasMany(Order::class,'customer_id');

    } 
    public function children(){
        return $this->hasMany(CustomerChild::class,'customer_id','id');
    }

    public function payment_profiles(){
        return $this->hasMany(CustomerPaymentProfile::class,'customer_id');
    }
    public function payments()
    {
        return $this->hasManyThrough(Payment::class, Order::class,'customer_id','membership_id');
    }
    public function totalMemberships()
    {
        return isset($this->children)?$this->children->count():0;
    }
    public function totalTripMember($trip_id)
    {
        $value = 0;
        foreach ($this->orders as $order)
        {
            $value = $value + $order->tripChildren()->where('trip_id',$trip_id)->count();
        }
        return  $value;
    }


    
    /**
     * The search by keyword.
     *
     * @string
     */

    public function scopeSearchByKeyword($query, $keyword)
    {
        if ($keyword!='') {
            $query->where(function ($query) use ($keyword) {
                $query->where("name", "LIKE","%$keyword%")
                    ->orWhere("email", "LIKE", "%$keyword%")
                    ->orWhere(function ($q) use ($keyword){
                        $q->whereHas('children',function ($q) use ($keyword){
                            $q->where("first_name", "LIKE","%$keyword%")
                            ->orWhere("last_name", "LIKE","%$keyword%");
                        });
                    });
            });
        }
        return $query;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function emails()
    {
        return $this->hasMany(CustomerEmail::class, 'customer_id');
    }
    public function getNewTripMailVariables($trip)
    {
        return array(
            '[member]' => ucfirst($this->name),
            '[close_at]' => $trip->booking_close->format('m/d/Y H:i A' ),
            '[limit]' => $trip->limit,
            '[link]' => url('/'),
        );
    }
}

resources/views/admin/users/__form.blade.php
<div class="box-body">

	<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
		<label for="full_name" class="col-sm-3 control-label field-required">Full Name</label>
	
		<div class="col-sm-7">
			<input type="text" name="name" class="form-control" id="full_name" placeholder="John Doe"
					value="{{ old('name') ? old('name') : '' }}">
			@foreach($errors->get('name') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>

	<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
		<label for="email" class="col-sm-3 control-label field-required">Email</label>

		<div class="col-sm-7">
			<input type="email" name="email" class="form-control" id="email" placeholder="someone{{'@'}}somewhere.com"
					value="{{ old('email') ? old('email') : '' }}">
			@foreach($errors->get('email') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>

	<div class="form-group {{ $errors->has('type') ? 'has-error' : '' }}">
		<label for="type" class="col-sm-3 control-label field-required">Type</label>

		<div class="col-sm-7">
			<select name="type" id="input" class="form-control" required="required">
				<option value="">Select</option>
				<option value="admin" @if (old('type') == 'admin') selected @endif>Admin</option>
				<option value="staff" @if (old('type') == 'staff') selected @endif>Staff</option>

			</select>
			@foreach($errors->get('type') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
			
		</div>
	</div>


	<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}" data-password-container>
		<label for="password" class="col-sm-3 control-label field-required">Password</label>

		<div class="col-sm-9">
			<input type="password" name="password" class="form-control" id="password" placeholder="Secret123" data-password style="max-width: 150px;">
			@if (!$errors->has('password'))
				<p class="help-block" style="position: absolute;top: 0;left: 173px;">Password must be at least 6 character.</p>
			@endif
			@foreach($errors->get('password') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>

	<div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}" data-password-confirmation-container>
		<label for="password_confirmation" class="col-sm-3 control-label field-required">Confirm Password</label>

		<div class="col-sm-9">
			<input type="password" name="password_confirmation" class="form-control" id="password_confirmation" placeholder="Secret123" data-password-confirmation style="max-width: 150px;">
		
			@foreach($errors->get('password_confirmation') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>
    
	<div class="form-group {{ $errors->has('email_details') ? 'has-error' : '' }}" data-email-details-container>
		<label for="email_details" class="col-sm-3 control-label"></label>


		<div class="col-sm-8">
                        <input type="checkbox" name="email_details" 
                        	id="email_details" 
                        	data-email-details style="margin-right: 4px;  vertical-align: sub;">Email details to new Admin
                        @foreach($errors->get('email_details') as $message)
                                <span class="help-block">{{ $message }}</span>
                        @endforeach
		</div>
	</div>
    </div>

</div>
<!-- /.box-body -->

resources/views/admin/users/__form_edit.blade.php
<div class="box-body">

	<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
		<label for="full_name" class="col-sm-3 control-label field-required">Full Name</label>

		<div class="col-sm-7">
			<input type="text" name="name" class="form-control" id="full_name" placeholder="John Doe"
					value="{{ old('name') ? old('name') : (isset($user) ? $user->name : '') }}">
			@foreach($errors->get('name') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>

	<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
		<label for="email" class="col-sm-3 control-label field-required">Email</label>

		<div class="col-sm-7">
			<input type="email" name="email" class="form-control" id="email" placeholder="someone{{'@'}}somewhere.com"
					value="{{ old('email') ? old('email') : (isset($user) ? $user->email : '') }}">
			@foreach($errors->get('email') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>

	<div class="form-group {{ $errors->has('type') ? 'has-error' : '' }}">
		<label for="type" class="col-sm-3 control-label field-required">Type</label>

		<div class="col-sm-7">
			<select name="type" id="input" class="form-control" required="required">
				<option value="">Select</option>
				<option value="admin" @if ( $user->type  == 'admin') selected @endif>Admin</option>
				<option value="staff" @if ( $user->type  == 'staff') selected @endif>Staff</option>

			</select>
			@foreach($errors->get('type') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
			
		</div>
	</div>


	<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}" data-password-container>
		<label for="password" class="col-sm-3 control-label field-required">Password</label>

		<div class="col-sm-9">
			<input type="password" name="password" class="form-control" id="password" placeholder="Secret123" data-password style="max-width: 150px;">
			
			@if (!$errors->has('password'))
				<p class="help-block" style="position: absolute;top: 0;left: 173px;">Password must be at least 6 character.</p>
			@endif

			@foreach($errors->get('password') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>

	<div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}" data-password-confirmation-container>
		<label for="password_confirmation" class="col-sm-3 control-label field-required">Confirm Password</label>

		<div class="col-sm-9">
			<input type="password" name="password_confirmation" class="form-control" id="password_confirmation" placeholder="Secret123" data-password-confirmation style="max-width: 150px;">
			@foreach($errors->get('password_confirmation') as $message)
				<span class="help-block">{{ $message }}</span>
			@endforeach
		</div>
	</div>
    
	
    </div>

</div>
<!-- /.box-body -->

resources/views/admin/users/__includes.blade.php
@section('javascripts')
	<script>
		// makes password-confirmation field green if
		// passwords match and makes it red otherwise
		$('[data-password-confirmation]').on('keyup', function (e) {
			if($('[data-password]').val() === $(this).val()){
				$(this).closest('[data-password-confirmation-container]')
						.removeClass('has-error').addClass('has-success');
			} else {
				$(this).closest('[data-password-confirmation-container]')
						.removeClass('has-success').addClass('has-error');
			}
		});
	</script>
@stop

resources/views/admin/users/create.blade.php
@extends('layouts.default')

@section('title')
	Create Admin
	@parent
@stop

@include('admin.users.__includes')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">

	<div class="row">
		<div class="col-md-8">
			
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Create Admin</h3>
				</div>
				<div class="box-body">
					@include('shared.errors')
				</div>
				<form action="{{ route('admin.users.store') }}" method="POST" class="form-horizontal">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					@include('admin.users.__form')
					<div class="box-footer">
						<button type="submit" class="btn btn-primary">Create</button>
						<a href="{{ route('admin.users.index') }}" class="btn btn-default">Cancel</a>
						
					</div>
				</form>
			</div>
		</div>
	</div>

	</div>
</div>

@stop

@section('javascript')
<script>
    $(function(){
        $('#password, #password_confirmation').keyup(function(){
            password        = $('#password').val();
            confirmPassword = $('#password_confirmation').val();
            var green = '#00a65a';
            var red = '#dd4b39';
            var defaultColor = '';
            
            if(password.length > 2 && $.trim(confirmPassword) != ''){
                if(password === confirmPassword){
                    $('label[for=password_confirmation]').css('color', green);
                    $('#password_confirmation').css('border-color', green);
                }else{
                    $('label[for=password_confirmation]').css('color', red);
                    $('#password_confirmation').css('border-color', red);
                }
            }else{ //default label
                    $('label[for=password_confirmation]').css('color', defaultColor);
                    $('#password_confirmation').css('border-color', defaultColor);
            }
        });
    });
</script>
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.default')
@section('title')
	Edit Admin
	@parent
@stop


@include('admin.users.__includes')
@section('content')

<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">

		<div class="row">
			<div class="col-md-8">
				<!-- Horizontal Form -->
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Edit Your Profile</h3>
					</div>
					<!-- /.box-header -->
					<!-- form start -->
					
					<form action="{{ route('admin.users.update', $user) }}" method="POST" class="form-horizontal">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<input type="hidden" name="_method" value="PATCH">
						@include('admin.users.__form_edit', compact('user'))
						<div class="box-footer">
							<button type="submit" class="btn btn-primary ">Update</button>
							<a href="{{ route('admin.users.index') }}" class="btn btn-default">Cancel</a>
							
						</div>
						<!-- /.box-footer -->
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

@stop

@section('javascript')
<script>
    $(function(){
        $('#password, #password_confirmation').keyup(function(){
            password        = $('#password').val();
            confirmPassword = $('#password_confirmation').val();
            var green = '#00a65a';
            var red = '#dd4b39';
            var defaultColor = '';
            
            if(password.length > 2 && $.trim(confirmPassword) != ''){
                if(password === confirmPassword){
                    $('label[for=password_confirmation]').css('color', green);
                    $('#password_confirmation').css('border-color', green);
                }else{
                    $('label[for=password_confirmation]').css('color', red);
                    $('#password_confirmation').css('border-color', red);
                }
            }else{ //default label
                    $('label[for=password_confirmation]').css('color', defaultColor);
                    $('#password_confirmation').css('border-color', defaultColor);
            }
        });
    });
</script>
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.default')

@section('title')
	Manage Admins
	@parent
@stop

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">

	<div class="row">
		<div class="col-lg-6 col-md-8">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Manage Admins</h3>
				</div>

				
				
				<div class="box-body table-responsive ">

					@include('shared.errors')

					<table class="table table-striped table-hover">
						<tr>
							
							<th>Admin</th>
							<th>Email</th>
							<th>Type</th>
							
							<th class="text-center">Action</th>
						</tr>
						@foreach($users as $admin)
							@if ($admin->id != 1)
								<tr data-delete="{{ route('admin.users.destroy', $admin) }}">

									<td>{{ $admin->name }}</td>
									<td>{{ $admin->email }}</td>
									<td>{{ ucfirst($admin->type) }}</td>
									<td class="text-center">
										<span class="">
											<a href="#"  data-delete-trigger><i class="fa fa-trash"></i></a>
											
										</span>
									</td>
								</tr>
							@endif
						@endforeach
					</table>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
	</div>

	<a class="btn btn-primary" href="{{ route('admin.users.create') }}">Add Admin</a>

		</div>
	</div>

@stop