routes/web.php
<?php

include __DIR__ . '/aritsan_routes.php';
Route::get('test',function (){
    return view('vendor\notifications\email');
    $order = \App\Models\Order::whereNotNull('trip_id')->first();
//    dd($order);
    return $order->childrenNamePriceTrip();
});
Route::get('logs', 'LogViewerController@index');

// Authentication Routes...
$this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login')->name('do-login');
$this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/request', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Admin Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for admin role
|	, 'middleware' => ['auth', 'role:admin']
*/
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin|staff']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin']], function () {

    // user managmet
    Route::resource('users', 'AdminController');
    Route::resource('pages', 'PageController');

    // settigns routes group
    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/site_settings', 'SettingController@siteSetting')->name('site');
        Route::post('/site_settings', 'SettingController@storeSiteSetting')->name('store.site');

        Route::get('general', 'SettingController@showGeneral')->name('general');
        Route::post('general', 'SettingController@updateGeneral')->name('general');

        Route::get('mail', 'SettingController@showMail')->name('mail');
        Route::post('mail', 'SettingController@updateMail')->name('mail');

        Route::post('send-email', 'SettingController@sendEmail')->name('send-email');

        Route::get('gateway', 'SettingController@showGateway')->name('gateway');
        Route::get('admin-gateway', 'SettingController@showGatewayAdmin')->name('gateway-admin');
        Route::post('gateway', 'SettingController@updateGateway')->name('gateway');

        Route::delete('{setting_id}/email/{email?}', [
            'as' => 'destroy_email',
            'uses' => 'SettingController@destroy_email'
        ]);

        Route::get('/twilio', 'SettingController@twilioSetting')->name('twilio');
        Route::post('/twilio', 'SettingController@storeTwilioSetting')->name('store.twilio');
        
    });

});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::group(['as'=>'admin.'], function () {
        Route::resource('home', 'HomePageController');
    });
});


/*
|--------------------------------------------------------------------------
| AuthUsers Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for authenticated Users
|
*/

Route::group(['namespace' => 'AuthUsers', 'middleware' => ['auth']], function () {

    Route::get('index', 'SampleController@index')->name('index');

});


/*
|--------------------------------------------------------------------------
| App Guest Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes unauthenticated users
|
*/

Route::group(['namespace' => 'App'], function () {


});


Route::get('log', function () {
    // from PHP documentations
    $logFile = file(storage_path() . '/logs/laravel.log');
    $logCollection = [];
    // Loop through an array, show HTML source as HTML source; and line numbers too.
    foreach ($logFile as $line_num => $line) {
        $logCollection[] = array('line' => $line_num, 'content' => htmlspecialchars($line));
    }
    dump($logFile);
});

Route::get('log/delete', function () {

    $file = storage_path() . '/logs/laravel.log';
    if (unlink($file)) {
        dump('deleted');
    }


});

Route::get('/home', 'FrontendController@homepage')->name('home');

//-------------------- Email Template Module -------------------//
Route::resource('email_templates','EmailTemplateController');
//-------------------- End ------------------------------------//

app/Models/EmailTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class EmailTemplate extends Model
{
    const NEW_MEMBER = 'New Member';
    const FAILED_TRANSACTION = 'Failed Transaction';
    const TRIP_PURCHASE = 'Trip Purchase';   
    const NEW_TRIP = 'New Trip Started';
    const REFUND_ISSUED = 'Refund Issued';//20
    const REFUND_FOR_EPIC_PASS = 'Refund for Epic Pass';//21
    const CANCELLATION_REFUND = 'Cancellation Refund';//22
    const CHARGE_FOR_PARENT_BUS_FEE = 'Charge for Parent Bus Fee';//23
    const CHARGE_FOR_LIFT_TICKET = 'Charge for Lift Ticket';//24
    const CHARGE_FOR_EQUIPMENT_RENTAL = 'Charge for Equipment Rental';//25


    protected $appends = ['variables', 'email_body'];


    public function scopeBySubject($query, $type)
    {
        return $query->where('subject', '=', trim($type));
    }

    public function createEmailBody($searchReplace)
    {
        $message = $this->replaceVariables($searchReplace);

        $message = $message . ' ' . $this->dynamic_body;

        $message = nl2br($message);
        $message = html_entity_decode(utf8_decode($message));

        return $message;
    }


    public function replaceVariables($searchReplace)
    {

        $message = $this->static_body;

        if (!config('site.enable_sales_tax')) {
            
            $message = str_replace('Sub Total:  [sub_total]','',$message ); 
            $message = str_replace('Sales Tax:  [sales_tax]','',$message ); 
        }

        foreach ($searchReplace as $key => $value) {

            $message = str_replace($key, $value, $message);
        }

        return $message;

    }

    /**
     * @return array
     */
    public function getVariablesAttribute()
    {
        if ($this->static_body) {

            preg_match_all('#\[(.*?)\]#', $this->static_body, $match);
            return $match[0];
        }

        return [];
    }

    /**
     * @return mixed|string
     */
    public function getEmailBody($searchReplace, $proposed_variables = null)
    {
        $this->email_body = $this->createEmailBody($searchReplace) . $proposed_variables;

        return $this;
    }

}

app/Http/Controllers/EmailTemplateController.php
<?php

namespace App\Http\Controllers;

use App\Models\EmailTemplate;
use Illuminate\Http\Request;
use Session;
use DB;

class EmailTemplateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $email_templates = EmailTemplate::all();
        return view('email_templates.index')->with('email_templates',$email_templates);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('email_templates.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required',
            'subject'=>'required',
            'fixed_body'=>'required',
        ]);
        if ($request->id>0) {
            $record=EmailTemplate::find($request->id);
            Session::flash('success','Updated Successfully');
        }else{
            Session::flash('success','Added Successfully');
            $record=new EmailTemplate;
        }
        $record->title=$request->title;
        $record->subject=trim($request->subject);
        $record->static_body=$request->fixed_body;
        $record->dynamic_body=$request->email_body;
            
            
        $record->save();
        return redirect('email_templates');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\EmailTemplate  $emailTemplate
     * @return \Illuminate\Http\Response
     */
    public function show(EmailTemplate $emailTemplate)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\EmailTemplate  $emailTemplate
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   

        $emailTemplate = EmailTemplate::find($id);

         return view('email_templates.edit',compact('emailTemplate'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\EmailTemplate  $emailTemplate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, EmailTemplate $emailTemplate)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\EmailTemplate  $emailTemplate
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            EmailTemplate::destroy($id);
            return response()->json('success', 200);
        } catch (\Exception $e) {
            return response()->json('error', $e->getCode());
        }
    }

 

    
}

resources/views/email_templates/create.blade.php
@extends('layouts.default')
@section('title',  'Create Template')
@section('styles')
@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">

                <div class="box-header">
                    <div class="row">
                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                            <h3 class="box-title">Create Template</h3>
                            <p class="m-t-10">
                                <a href="{{ route('email_templates.index') }}" class="btn btn-default">Back</a>
                            </p>
                        </div>

                    </div>
                </div> <!-- box-header -->

                <div class="box-body">

                    {{-- Errors and messages --}}
                    @include('shared.errors')
                    {{-- // Errors and messages --}}

                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                            <form action="{{url('')}}/email_templates" method="post" enctype="multipart/form-data">
                              
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type = "hidden" name = "id" value = "0">
                                   
                                    
                                       
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="field-required">Display Title</label>
                                                            <input type="text"  value="{{old('title')?old('title'):''}}"  class="form-control" name="title">
                                                        </div>
                                                       
                                                        <div class="form-group">
                                                            <label class="field-required">Subject</label>
                                                            <input type="text"  value="{{old('subject')?old('subject'):''}}"  class="form-control" name="subject">
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="field-required">Fixed Body</label>
                                                            <textarea class="form-control mceEditor" name="fixed_body">{{old('fixed_body')?old('fixed_body'):''}}</textarea>
                                                            
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="">Email Body</label>
                                                            <textarea  class="form-control mceEditor"  name="email_body">{{old('email_body')?old('email_body'):''}}</textarea>
                                                            
                                                        </div>
                                                        
                                                        

                                                    </div>
                                                    
                                                </div>


                                        <button class="btn btn-success" type="submit">Add</button>
                                 
                                
                            </form>
                        </div>
                    </div> <!-- row -->

                </div><!-- /.box-body -->
            </div>

        </div>
    </div>
        </section>
    </div>
@endsection

@section('scripts')

@endsection

resources/views/email_templates/edit.blade.php
@extends('layouts.default')
@section('title',  'Edit Template')
@section('styles')
@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">

                <div class="box-header">
                    <div class="row">
                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                            <h3 class="box-title">Edit Template</h3>
                            <p class="m-t-10">
                                <a href="{{ route('email_templates.index') }}" class="btn btn-default">Back</a>
                            </p>
                        </div>

                    </div>
                </div> <!-- box-header -->

                <div class="box-body">

                    {{-- Errors and messages --}}
                    @include('shared.errors')
                    {{-- // Errors and messages --}}

                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                            <form action="{{url('')}}/email_templates" method="post" enctype="multipart/form-data">
                        
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type = "hidden" name = "id" value = "{{$emailTemplate->id}}">
                            {{--<!-- text input -->--}}
                            
                                        <div class="row">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="field-required">Display Title</label>
                                                    <input type="text"  value="{{old('title')?old('title'):$emailTemplate->title}}"  class="form-control" name="title">
                                                </div>
                                              
                                                <div class="form-group">
                                                    <label class="field-required">Subject</label>
                                                    <input type="text" readonly value="{{old('subject')?old('subject'):$emailTemplate->subject}}"  class="form-control" name="subject">
                                                </div>
                                            </div>
                                         </div>
                                         <div class="row">
                                            
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="field-required">Fixed Body</label>
                                                    <textarea rows="10"  class="form-control "  name="fixed_body">{{  strip_tags($emailTemplate->static_body) }}</textarea>
                                                    
                                                </div>
                                                <div class="form-group">
                                                    <label class="">Email Body</label>
                                                    <textarea rows="10"  class="form-control mceEditor"  name="email_body">{{old('email_body')?old('email_body'):$emailTemplate->dynamic_body}}</textarea>
                                                    
                                                </div>
                                            </div> 
                                        </div>  

                                    

                                <button class="btn btn-primary" type="submit">Update</button>
                           
                    </form>

                        </div>
                    </div> <!-- row -->

                </div><!-- /.box-body -->
            </div>

        </div>
    </div>
        </section>
    </div>
@endsection

@section('scripts')

@endsection

resources/views/email_templates/index.blade.php
@extends('layouts.default')
@section('title',  'Email Template Listing')
@section('styles')
@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box">

                        <div class="box-header">
                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                    <h3 class="box-title">Email Template Listing</h3>
                                    <p class="m-t-10">
                                        {{--<a href="{{url('email_templates/create')}}" class="btn btn-success">Add Template</a>--}}
                                    </p>
                                </div>

                            </div>
                        </div> <!-- box-header -->

                        <div class="box-body">

                            {{-- Errors and messages --}}
                            @include('shared.errors')
                            {{-- // Errors and messages --}}

                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                                    <table class="table table-responsive table-bordered table-striped">
                                        <tr>
                                            <th>Title</th>
                                            <th>Subject</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                        @if(count($email_templates)>0)
                                            @foreach($email_templates as $i)
                                                <tr data-delete="{{ route('email_templates.destroy', $i) }}">

                                                    <td>{{$i->title}}</td>
                                                    <td>{{$i->subject}}</td>

                                                    <td class="text-center">
                                                        <a href="{{route('email_templates.edit', $i->id)}}"
                                                           class="fa fa-pencil"></a>

                                                    </td>
                                                </tr>
                                            @endforeach
                                        @else
                                            <tr>
                                                <td colspan="5">No results found in Email Templates</td>
                                            </tr>
                                        @endif
                                    </table>
                                </div>
                            </div> <!-- row -->

                        </div><!-- /.box-body -->
                    </div>

                </div>
            </div>
        </section>
    </div>
@endsection

@section('scripts')

    <script>

        jQuery(document).ready(function ($) {
            $('#form-submit').on('click', function (event) {
                event.preventDefault();
                $('form').submit();
            });
        });

    </script>

@endsection