routes/web.php
<?php

include __DIR__ . '/aritsan_routes.php';
Route::get('test',function (){
    return view('vendor\notifications\email');
    $order = \App\Models\Order::whereNotNull('trip_id')->first();
//    dd($order);
    return $order->childrenNamePriceTrip();
});
Route::get('logs', 'LogViewerController@index');

// Authentication Routes...
$this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login')->name('do-login');
$this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/request', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Admin Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for admin role
|	, 'middleware' => ['auth', 'role:admin']
*/
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin|staff']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:admin']], function () {

    // user managmet
    Route::resource('users', 'AdminController');
    Route::resource('pages', 'PageController');

    // settigns routes group
    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/site_settings', 'SettingController@siteSetting')->name('site');
        Route::post('/site_settings', 'SettingController@storeSiteSetting')->name('store.site');

        Route::get('general', 'SettingController@showGeneral')->name('general');
        Route::post('general', 'SettingController@updateGeneral')->name('general');

        Route::get('mail', 'SettingController@showMail')->name('mail');
        Route::post('mail', 'SettingController@updateMail')->name('mail');

        Route::post('send-email', 'SettingController@sendEmail')->name('send-email');

        Route::get('gateway', 'SettingController@showGateway')->name('gateway');
        Route::get('admin-gateway', 'SettingController@showGatewayAdmin')->name('gateway-admin');
        Route::post('gateway', 'SettingController@updateGateway')->name('gateway');

        Route::delete('{setting_id}/email/{email?}', [
            'as' => 'destroy_email',
            'uses' => 'SettingController@destroy_email'
        ]);

        Route::get('/twilio', 'SettingController@twilioSetting')->name('twilio');
        Route::post('/twilio', 'SettingController@storeTwilioSetting')->name('store.twilio');
        
    });

});


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::group(['as'=>'admin.'], function () {
        Route::resource('home', 'HomePageController');
    });
});


/*
|--------------------------------------------------------------------------
| AuthUsers Protected Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes for authenticated Users
|
*/

Route::group(['namespace' => 'AuthUsers', 'middleware' => ['auth']], function () {

    Route::get('index', 'SampleController@index')->name('index');

});


/*
|--------------------------------------------------------------------------
| App Guest Routes
|--------------------------------------------------------------------------
|
| Here you can register web routes unauthenticated users
|
*/

Route::group(['namespace' => 'App'], function () {


});


Route::get('log', function () {
    // from PHP documentations
    $logFile = file(storage_path() . '/logs/laravel.log');
    $logCollection = [];
    // Loop through an array, show HTML source as HTML source; and line numbers too.
    foreach ($logFile as $line_num => $line) {
        $logCollection[] = array('line' => $line_num, 'content' => htmlspecialchars($line));
    }
    dump($logFile);
});

Route::get('log/delete', function () {

    $file = storage_path() . '/logs/laravel.log';
    if (unlink($file)) {
        dump('deleted');
    }


});

Route::get('/home', 'FrontendController@homepage')->name('home');

//-------------------- Email Template Module -------------------//
Route::resource('email_templates','EmailTemplateController');
//-------------------- End ------------------------------------//

app/Setting.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Log; 
use Artisan;

class Setting extends Model {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'settings';
    protected $guarded = [];

    public function updateConfig($data)
    {
        // rewriting old config's values. This way
        // no 'key => value' pair gets deleted accidentally
        Log::info($data);
        $this->config = @$this->config ? array_merge($this->config, $data) : $data;
        Log::info($this->config);
        
        // invalidate the obsolete cache
        Artisan::call('cache:clear');
        Cache::forget('mail');

        $this->save();
    }

    public function customUpdate(Request $request)
    {
        $newConfig = $request->only('config')['config'];

        if($request->hasFile('config.print_logo_file')) {
            $this->handleUploadedLogo($request);
        }

        // rewriting old config's values. This way
        // no 'key => value' pair gets deleted accidentally
        $this->config = $this->config ? array_merge($this->config, $newConfig) : $newConfig;

        // invalidate the obsolete cache
        Cache::forget($this->key);

        $this->save();
    }

    private function handleUploadedLogo(Request $request)
    {
        $uploadedLogo = $request->file('config.print_logo_file');

        if ($uploadedLogo->isValid()) {
            $this->deleteOldLogo();
            $this->persistNewLogo($uploadedLogo);
        }
    }

    public function deleteOldLogo()
    {
        if (isset($this->config['print_logo']) && $this->config['print_logo']) {
            File::delete(base_path(env('UPLOADS_RELATIVE_PATH') . DIRECTORY_SEPARATOR . $this->config['print_logo']));
        }
    }

    private function persistNewLogo(UploadedFile $uploadedLogo)
    {
        $fileName = $this->generateFileName($uploadedLogo);
        $uploadedLogo->move(base_path(env('UPLOADS_RELATIVE_PATH')), $fileName);

        $this->persistNewLogoName($fileName);
    }

    private function persistNewLogoName($fileName)
    {
        $config = $this->config;
        $config['print_logo'] = $fileName;
        $this->config = $config;
    }

    private function generateFileName(UploadedFile $uploadedFile)
    {
        return 'print_logo.' . $uploadedFile->getClientOriginalExtension();
    }

    public function removeEmail($email)
    {
        $config = $this->config;

        $key = array_search($email, $config['additional_emails']);

        // $key might be 0, hence the strict comparison
        if($key !== false) unset($config['additional_emails'][$key]);

        $this->config = $config;

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Getters / Setters
    |--------------------------------------------------------------------------
    */

    /**
     * @return array
     */
    public function getConfigAttribute()
    {
        $config = json_decode($this->attributes['config'], true);

        return $config ? $config : [];
    }

    /**
     * @return array
     */
    public function getValidationRulesAttribute()
    {
        $validationRules = json_decode($this->attributes['validation_rules'], true);

        return $validationRules ? $validationRules : [];
    }

    /**
     * @param array
     */
    public function setConfigAttribute(array $config)
    {
        $this->attributes['config'] = json_encode($config);
    }

    /**
     * In case if someone attempts to change validation rules
     * from within the app, an exception will be thrown
     *
     * @throws \Exception
     * @param array
     */
    public function setValidationRulesAttribute(array $validationRules)
    {
        throw new \Exception('The validation rules are immutable!');
    }
}

app/Http/Controllers/Admin/SettingController.php
<?php namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Session,Cache;
use App\Setting;
use App\Http\Requests\SendEmailRequest;
use App\Http\Controllers\EmailController;
use App\EmailHisotry;
use DOMDocument;
use Twilio\Rest\Client;

class SettingController extends Controller {

   

    protected $viewsFolder = 'settings.';

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function siteSetting()
    {
        $setting = Setting::query()->where('key', 'site')->first();
        $config = $setting ? (object) @$setting->config : (object) config('site');
        \Cache::forget('site');
        return view('settings.site', compact('setting', 'config'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function storeSiteSetting(Request $request)
    {
        $setting = Setting::query()->firstOrNew([
            'key' => 'site',
            'view_name' => 'settings.site',
            'title' => 'Site Settings',
        ]);
//        dd($setting,$request->config);
        $setting->updateConfig($request->config);

        $request->session()->flash('success', 'Updated successfully!');
        return redirect(route('admin.settings.site'));
    }


    public function showGeneral()
    {
        $setting = Setting::where('key','general')->first();
       
        $config = $setting->config;

        Cache::forget('general');
        
        return view($this->viewsFolder.'general', compact('setting', 'config'));
    }


     public function updateGeneral(Request $request)
    {   
        $input = $request->all();
        
        $this->validateGenral($request);

        $setting = Setting::where('key','general')->first();
        $setting->updateConfig($input['config']); 

        Session::flash('success', "Settings were updated successfully");

        return back();
    }


	public function showMail()
	{
		$setting = Setting::where('key','mail')->first();
                $config = $setting->config;
                $emails = EmailHisotry::getRecent();
		return view($this->viewsFolder.'mail', compact('setting', 'config', 'emails'));
	}


    public function updateMail(Request $request)
    {   
        $input = $request->all();
        
        if ($input['config']['driver'] == 'mailgun') {
            $this->validateMailgun($request);
        }

        if ($input['config']['driver'] == 'smtp') {
           $this->validateSMTP($request);
        }

        $setting = Setting::where('key','mail')->first();
        $setting->updateConfig($input['config']); 

        Session::flash('success', "Settings were updated successfully");

        return back();
    }
	
    public function destroy_email($setting_id, $email = "")
    {
        $setting = Setting::find($setting_id);

        $success = $setting->removeEmail($email)->save();

        return response()->json(compact('success'));
    }

    public function validateMailgun($request)
    {
        
        $rules = [
            
            'config.from.name' => 'required',
            'config.from.address' => 'required|email',
            'config.secret' => 'required',
            'config.domain' => 'required',
        ]; 

        $this->validate($request,$rules); 

    }


    public function validateSMTP($request)
    {
        
        $rules = [
            'config.host' => 'required',
            'config.port' => 'required|numeric',
            'config.username' => 'required',
            'config.password' => 'required',
            'config.from.name' => 'required',
            'config.from.address' => 'required|email',
        ]; 

        $this->validate($request,$rules); 

    }


    public function validateGenral($request)
    {
        
        $rules = [
            'config.site_name' => 'required',
            'config.site_url' => 'required',
            'config.default_email' => 'required',
        ]; 

        $this->validate($request,$rules); 

    }
    
    public function sendEmail(SendEmailRequest $request)
    {   

        // Create array of data 
         $emailData = [ 
          'action' => 'email', // view , email 
          'template' => 'simple', 
          'subject' => 'Test Email',
          'to' => $request->get('to'), 
          'emailContent' => [ 
              'message' => $request->get('message'), 
              ]
        ];
        // send email 
        $sent = sendEmail($emailData);
        
        if($sent)
        {
            Session::flash('success', "Email sent successfully!");
            return back();
            
        } else {
            Session::flash('error', "Email sending failed!");
            return back()->withInput();
            
        }
    }
    
    public function showGateway($value='')
    {
        $setting = Setting::where('key','gateway')->first();
        $config = $setting->config;
        return view( 'settings.gateway', compact('setting', 'config'));
    }


    public function showGatewayAdmin($value='')
    {
        $setting = Setting::where('key','gateway')->first();

        $config = $setting->config;


        return view( 'settings.gateway-admin', compact('setting', 'config'));
    }


    public function updateGateway(Request $request)
    {
       $input = $request->all();

       $this->validateGateway($request);

       $setting = Setting::where('key','gateway')->first();
       
       $setting->updateConfig($input['config']);
       \Cache::forget('gateway');

       Session::flash('success', "Settings were updated successfully");

       return back();
    }


    public function validateGateway($request)
    {

        $rules = [
            'config.mode' => 'required|in:0,1',
            'config.mode' => 'required',
        ];

        $this->validate($request,$rules);

    }

    public function twilioSetting()
    {
        $messages = [];
        $error = null;

        $setting = Setting::query()->where('key', 'twilio')->first();


//        if(! $setting) {
//            return view('setting.twilio', compact('twilioSetting', 'messages', 'error'));
//        }

        $twilioSetting = $setting ? (object) @$setting->config : (object) config('twilio');

        // try {
        //     $client = new Client(@$twilioSetting->sid, @$twilioSetting->token);
        //     // Get Recent Calls
        //     foreach ($client->account->messages->read() as $key => $call) {

        //         $dateCreated = (array)$call->dateCreated;

        //         $messages[$key]['from'] = $call->from;
        //         $messages[$key]['to'] = $call->to;
        //         $messages[$key]['body'] = $call->body;
        //         $messages[$key]['date'] = date('m/d/Y  H:s', strtotime($dateCreated['date']));
        //         $messages[$key]['status'] = $call->status;

        //         //$time = $call->startTime->format("Y-m-d H:i:s");
        //         //echo "Call from $call->from to $call->to body: $call->body \n";
        //     }
        // } catch (\Exception $e) {
        //     $error  = $e->getMessage();
        // }

        return view('settings.twilio', compact('twilioSetting', 'messages', 'error'));
    }


    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function storeTwilioSetting(Request $request)
    {
        $this->validate($request, [
            'config.sid' => 'required',
            'config.token' => 'required',
            'config.from' => 'required',
        ]);

        $setting = Setting::query()->firstOrNew([
            'key' => 'twilio',
            'view_name' => 'settings.twilio',
            'title' => 'Twilio Settings',
        ]);

        $setting->updateConfig($request->config);

        $request->session()->flash('success', 'Settings saved.');
        return back();
    }
    

}

resources/views/settings/general.blade.php
@extends('layouts.default')
@section('title')
    General Settings
    @parent
@stop


@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">

            <form action="{{ route('admin.settings.general', $setting) }}" method="post" enctype="multipart/form-data">

                <div class="row">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    <div class="col-lg-6 col-md-5">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="box">
                                    <div class="box-header">
                                        <h3 class="box-title">{{ $setting->title }}
                                            <small>{{ $setting->description }}</small>
                                        </h3>
                                    </div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group {{ $errors->has('config.site_name') ? 'has-error' : '' }}">
                                                    <label for="site-name" class="field-required">Site name</label>
                                                    <input name="config[site_name]" id="site-name"
                                                           type="text" class="form-control"
                                                           placeholder="Example Services"
                                                           value="{{ old('config.site_name') ? old('config.site_name') : $config['site_name'] }}">
                                                    @foreach($errors->get('config.site_name') as $message)
                                                        <span class="help-block text-danger">{{ $message }}</span>
                                                    @endforeach
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group {{ $errors->has('config.site_url') ? 'has-error' : '' }}">
                                                    <label for="site-url" class="field-required">Site url</label> <input
                                                            name="config[site_url]" id="site-url"
                                                            type="url" class="form-control"
                                                            placeholder="http://example.com"
                                                            value="{{ old('config.site_url') ? old('config.site_url') : $config['site_url'] }}">
                                                    @foreach($errors->get('config.site_url') as $message)
                                                        <span class="help-block text-danger">{{ $message }}</span>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group {{ $errors->has('config.default_email') ? 'has-error' : '' }}">
                                                    <label for="default-email" class="field-required">Default
                                                        email</label>
                                                    <input name="config[default_email]" id="default-email"
                                                           type="email" class="form-control"
                                                           placeholder="example{{'@'}}somewhere.com"
                                                           value="{{ old('config.default_email') ? old('config.default_email') : $config['default_email'] }}">
                                                    @foreach($errors->get('config.default_email') as $message)
                                                        <span class="help-block text-danger">{{ $message }}</span>
                                                    @endforeach
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group {{ $errors->has('config.phone') ? 'has-error' : '' }}">
                                                    <label for="phone" class="field-required">Phone</label>
                                                    <input name="config[phone]" id="phone"
                                                           type="text" class="form-control phonebox" placeholder=""
                                                           value="{{ old('config.phone') ? old('config.phone') : @$config['phone'] }}">
                                                    @foreach($errors->get('config.phone') as $message)
                                                        <span class="help-block text-danger">{{ $message }}</span>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>

                    <div class="col-lg-6 col-md-7">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title m-b-10">Additional Emails</h3>

                            </div>
                            <div class="box-body">
                                <div class="box-tools">
                                    <input data-add
                                           type="email"
                                           class="form-control"
                                           placeholder="someone{{'@'}}somewhere.com"
                                           style="width:200px; display:inline-block">

                                    <a data-add-trigger
                                       class="btn btn-primary btn-sm" href="#"
                                       style="display:inline-block; margin: 0 5px 4px 0;">Add</a>

                                </div>
                            </div>
                            <br>
                            <!-- /.box-header -->
                            <div class="box-body table-responsive no-padding">
                                <table class="table table-striped">
                                    <tbody data-add-target>
                                    <tr>
                                        <th>#</th>
                                        <th>Email</th>
                                        <th>Status</th>
                                        <th style="width: 40px"></th>
                                    </tr>
                                    <?php $i = 0; ?>
                                    @foreach($config['additional_emails'] as $additional_email)
                                        <tr data-delete="{{ route('admin.settings.destroy_email', [
															'setting_id' => $setting->id,
															'email' => $additional_email
														])
									}}">
                                            <td>{{ ++$i }}.</td>
                                            <td>{{ $additional_email }}</td>
                                            <td><span class="label label-success">Approved</span></td>
                                            <td><a class="btn btn-danger btn-xs" href="#" data-delete-trigger>Delete</a>
                                            </td>
                                            <input type="hidden" name="config[additional_emails][]"
                                                   value="{{ $additional_email }}">
                                        </tr>
                                    @endforeach

                                    {{-- Template for new entries --}}
                                    <tr style="display:none;" data-template data-delete>
                                        <td></td>
                                        <td><span class="label label-warning">Pending</span></td>
                                        <td>
                                            <a class="btn btn-danger btn-xs" href="#" data-delete-trigger="no-confirm">Delete</a>
                                        </td>
                                        <input type="hidden" value="">
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.box-body -->
                        </div>


                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <button type="submit" class="btn btn-primary">Update Settings</button>
                    </div>
                </div>
                <!-- ./row -->
            </form>

        </section>
    </div>

@stop



@section('javascript')

    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>

    <script>
        $(document).on('click', '[data-add-trigger]', function (event) {
            event.preventDefault();
            alert('hi');
            // extract value from input and clear it
            var $emailField = $('[data-add]');
            var newEmail = $emailField.val();

            if (!newEmail) {
                return;
            }

            $emailField.val('');

            // the table which holds additional emails
            var $table = $('[data-add-target]');

            // entry template
            var $template = $('[data-template]');
            var $newEntry = $template.clone();

            // prepare the template
            $newEntry.removeAttr('style').removeAttr('data-template');
            $newEntry.find('input').attr('name', 'config[additional_emails][]').val(newEmail);

            // find out the entry number for the new entry
            var number = Number($table.find('tr').last().prev().find('td:nth-child(1)').text());
            number = number ? ++number : 1;

            // set the entry number and email
            $newEntry.find('td:nth-child(1)').text(number + '.');
            $newEntry.find('td:nth-child(2)').text(newEmail);

            // add the new entry before the template
            $template.before($newEntry);
        });
    </script>



    <script>
        $('#image-upload').change(function () {
            var $imageUploadLabel = $('[for=image-upload]');

            if ($(this).val()) {
                $imageUploadLabel.removeClass('btn-default');
                $imageUploadLabel.addClass('btn-warning');
            } else {
                $imageUploadLabel.addClass('btn-warning');
                $imageUploadLabel.removeClass('btn-default');
            }
        });
    </script>

@stop